-
  name: Chong-Min Kyung
  description: Chong-Min Kyung is Professor at the Department of Electrical Engineering(EE) at KAIST and Director of Center for Integrated Smart Sensors(CISS), funded as Global Frontier Project by Korean government. He is responsible for all operations and overall strategic direction of CISS. His research interest is low-energy 3-D camera system design. Previously, Prof. Kyung worked at Bell Telephone Murray Hill. He received Ph.D. in EE at KAIST 1981. He is IEEE Fellow.
  company: CISS
  picture: Chong-Min  Kyung 2.jpg
-
  name: Dongik Kim
  description: Dongik Kim is a research associate professor at CISS. He has expertise in IR Image sensor module and IR optical system design. He is working on Dual and multi-aperture optical system design for CMOS cameras at CISS. Before CISS, he was a postdoctoral associate at Korea Basic Science Institute. He received his Ph.D. from Sogang University in 2006.
  company: CISS
  picture: Dongik Kim.jpg
-
  name: Dongsuk Kim
  description: Dongsuk Kim is a research assistant professor at CISS. He has been working in the area of Image-based object detection for DAS (Driver Assistance Systems). Currently, he is developing Image-based object detection for driver assistance systems at CISS. Prior to CISS, he was a postdoctoral associate at Hanyang University. He did his Ph.D. from Sogang University in 2004.
  company: CISS
  picture: Dongsuk Kim.jpg
-
  name: Jongho Park
  description: Jongho Park is a research associate professor at CISS. He has been working on CMOS image sensor, being responsible for high sensitivity CIS design for Dual Aperture. He held the position of Executive Director/Principal Engineer at Brookman Technology, Inc. He received his Ph.D. from Shizuoka University (Japan) in 2007.
  company: CISS
  picture: Jongho Park.jpg
-
  name: Jun Ho Mun
  description: Jun Ho Mun is Head of Planning Department of Sharing and Technologies Inc. His research is on Optical System Design and Camera Lens System Optimization. Previously, he was a research center manager at Samsung Electro-mechanics. He received his Ph.D. from KAIST in 2001.
  company: CISS
  picture: Jun Ho Mun.jpg
-
  name: Ki-Yeong Park
  description: Ki-Yeong Park is a research assistant professor at CISS. His research is on Algorithm for Object Detection & Machine Learning. He is working on Development of multi-class and multi-view object detection platform. Prof. Park previously served as Head of Research Center at MIware Inc. He will receive his Ph.D. from Sogang University in August, 2014.
  company: CISS
  picture: Ki-Yeong Park.jpg
-
  name: Sang Gil Choi
  description: Sang Gil Choi is a research associate professor at CISS. His main expertise lies in development of 3D graphics accelerator chip design and IR imaging camera. He is currently working on Dual Aperture's application system at CISS. Prior to joining CISS, he was the head of research center at Krazevision Inc.. He received his Ph.D. from KAIST in 1992.
  company: CISS
  picture: Sang Gil Choi.jpg
-
  name: Seunghyuk Chang
  description: Seunghyuk Chang is a research associate professor at CISS. His areas of expertise are off-axis reflective imaging system, optical aberration theory. He is developing Image Sensor, IR Imaging System at CISS. Prior to joining CISS, he worked as senior researcher at Image Development Department, Samsung Electronics Co., Ltd. He got his Ph.D. in Computer Science at the University of Southern California.
  company: CISS
  picture: Seunghyuk Chang.jpg